"""empty message

Revision ID: 887402c48dd9
Revises: 
Create Date: 2025-04-08 22:01:46.093225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887402c48dd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_pet', sa.String(length=255), nullable=True),
    sa.Column('nome_propietario', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    # ### end Alembic commands ###
